### ISSUE TITLE
Things to do before Great Orwell

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#144]
** Now sorted in terms of importance**

# Important
- [ ] #180
# Nice to have
- [ ] German support (moving this to 5.1)

# Documentation
- [ ] Config object

# Tests
- [ ] Settings.yml

# Gifs
- [ ] Gif showing writing a program to import Ciphey

# Done
- [x] #172
- [x] Fix making your own ciphers https://github.com/Ciphey/CipheyDocs/issues/11
- [x] Full technical explanation of Ciphey
- [x] Using Ciphey (piping, unqualified text, custom regex, settings file)
- [x] Clean up root directory
- [x] New gif right at the start of the Ciphey README. Use something slightly hard, show we can actually do it.
- [x] Fix Brandon checker #155 
- [x] Brandon checker
- [x] Write more tests, specifically Click tests (Harlan but he'll force Brandon)
- [x] Add base8
- [x] Display help menu if no arguments are supplied
- [x] Rename `__main__` to ciphey so you can import  `from Ciphey.ciphey import main` instead of `from Ciphey.__main__ import ciphey` @Cyclic3 
- [x] Argparser to Click
- [x] Better documentation
- [x] Compare with Ciphey / CyberChef / Katana
- [x] Move documentation
- [x] CI broken pls fix (Cyclic3)
- [x] Add a spinner so users dont think the app has crashed and it seems faster than it it (Click has a spinner extension) (Harlan)
- [x] print appdirs argument 
- [x] fix #158
- [x] #159
- [x] Redesign readme (Brandon)
- [x] @Cyclic3 to fix #97 because there is no way I am touching that again, it makes me cry :( (HARLAN)
- [x] WinGet / Homebrew / AUR @Cyclic3 
- [x] more gifs
- [x] Add a spinner
- [x] #160
- [x] #161
- [x] #163
- [x] Adding a new cipher to Ciphey
