### ISSUE TITLE
Tag System

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#147]
# ToDo
- [ ] Add tags to all current ciphers / encodings
- [ ] Decode on a specific list of tags and include in our documentation
- [ ] Edit wiki page to talk about tag system (how to add your own cipher)

Sometimes we want to run specific subsets of crackers. An example is:
* Offline only crackers
* All crackers
* Default crackers
* Most popular crackers

## Implementation
AuSearch has a list of crackers. We remove crackers or add more to the list depending on the tags.

We build a tagging interface, with something like this:
```python
class tagging:
    def __init__(self):
        defaults = ["bases", "caesar"]
        online=["online"]
```

Basically, we categorise each cracker. Perhaps for each cracker, we give it an attribute containing a dictionary along with some information about what categories it falls into.

Then to build tags, we use a set theory implementation.
So to run defaults and online, we run:
```
--tag defaults U online
```
We would have to use some kind of resource selector, as writing set theory on the terminal is hard. 

The idea is that we show the user the categories, and the user constructs their own tags based on the categories. 

This addresses #143 and this Discord comment:
> we should add as many crackers as possible and just keep the most used ones the default, but add an option to allow to use all. We can calculate most used ones via the web app, that way we maintain speed with the default but if the user wants they can try the more esoteric stuff :)

**Comment by brandonskerritt** [comment]
Writing set theory with just your keyboard is hard. For example, there's no symbol for intersection unless you know the numpad combo.

That's why I suggest this algorithm:

`intersection = ["intersection", "⋂", "I", "Intersect"]`

An _operator_ is anything not in the set of categories:

`categories = set(basic.get_categories, encodings.get_categories)`

And also in the list of lists (we can make it a set)

```
operators = [intersection, union]
```

Therefore we have a rudimentary O(n^2 + n) algorithm:

```
to_do = []

for i in tags:
    if i not in categories:
        for y in operators:
            if i in y:
                to_do.append(i, y, i[+2])
```

The above code wouldn't work, but it's to illustrate.

**Comment by Cyclic3** [comment]
how about the words `and`, `or`, `not`. I heard they're all the rage these days with UX people!

On a more serious note, users are most likely to want a whitelist and a blacklist, rather than to invoke the axiom of choice.

**Comment by lukasgabriel** [comment]
The idea of a tagging system is great - it would give us (especially me since I like writing silly/niche decoders/crackers) a guilt-free (as in it does't slow down the rest of the application) way of adding more ciphers that might only be useful to some while keeping it all clean and focused on the essentials for the average user.

**Comment by bee-san** [comment]
Here are the categories I can imagine:
* Offline 
* Core approved (as in, crackers / decoders that the core team have created)
* Community
* Most popular (taken from our website, when we build it)
* Meme (the hint might be "funny number base encoding" or something)
* Crackers
* Encoders
* Hashes
* Base
* Transposition
* Modern ciphers

Any other suggestions?
