### ISSUE TITLE
6.0.0 release

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#591]
This is currently being undertaken, and as such the growth of Ciphey has slowed.

We are working towards:
* Removing CipheyCore
* Improving Language Checkers

- [ ] #612  <- This is currently being worked on 
- [ ] #641 <- This is currently being worked on 
- [ ] #642  <- @SkeletalDemise  has completed this locally but not made a PR
- [x] #626 and #628  <- This is being worked on

**Comment by bee-san** [comment]
#619 adds a new checker

**Comment by bee-san** [comment]
#612

**Comment by bee-san** [comment]
#628 ausearch is now in master!

**Comment by gruvw** [comment]
Will 6.0.0 support python 3.10 ?

**Comment by nm-remarkable** [comment]
> Will 6.0.0 support python 3.10 ?

What about python 3.11?
