### ISSUE TITLE
Add more decryption methods

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#63]
Here is a list of all the ciphers Ciphey plans to support. Pick one and implement it please :) <3 
Here's how to incorporate it into Ciphey:
https://github.com/Ciphey/Ciphey/wiki/Adding-your-own-ciphers
Full list of implemented ciphers:
https://github.com/Ciphey/Ciphey/wiki/Supported-Ciphers

# Easiest

* [ ] First letter of every word, first letter of every line, 2nd letter of every word etc (#336) 
* [ ] T9 phone keypad cipher (like the old Nokia phones) (#422)

# Ciphers / Encodings 
* [ ] Playfair cipher (#345)
* [ ] Badly implemented RSA
* [ ] Monoalphabetic Substitution Cipher (#347)
* [ ] Vigenère Autokey Cipher (#348)
* [ ] Beaufort Cipher (#349)
* [ ] Beaufort Autokey Cipher
* [ ] Columnar Transposition Cipher (#350)
* [ ] Railfence Cipher (#351)
* [ ] Double Transposition (#352)

# Done
* [x] Base8
* [x] Base58 https://github.com/keis/base58 (both Bitcoin & Ripple alphabets)
* [x] Base85
* [x] Base85 ASCII version (Python library for this)
* [x] Base 62 with alphabet `0-9A-Za-z`** (Most link shorteners use this alphabet, and it's the default in CyberChef + the online Base62 decoders)
* [x] Vigenere Cipher
* [x] Atbash Cipher
* [x] Base91
* [x] If a text only contains 2 letters X and Y, we may turn it into Binary and see if that works. similarly we could do the same for hex and octal etc
* [x] Minecraft enchanting table (see https://github.com/Ciphey/Ciphey/issues/63#issuecomment-669145486 )
* [x] XOR
* [x] Base69 (#335)
* [x] DNA codons (ATCG DNA letters) (#354)
* [x] Baudot ITA2 (#355)
* [x] SMS Multi-tap (#340)
* [x] DTMF frequency (#424)
* [x] A1Z26 (#344)
* [x] Prisoner's tap code (#337)
* [x] Brainfuck (#353)
* [x] ROT47 (#342)
* [x] ASCII shift (#343)
* [x] UUencode (#433)
* [x] Affine (#346)
* [x] Baconian cipher (#432)
* [x] Soundex (#412)
* [x] Braille (#439)

**Comment by brandonskerritt** [comment]
https://www.boxentriq.com/code-breaking/cryptogram

**Comment by brandonskerritt** [comment]
@Cyclic3 Just in case you didn't notice, this is the issue where I keep track of ciphers I've encountered in CTfs and want to implement :)

**Comment by brandonskerritt** [comment]
@Cyclic3 sent this to me:
```
["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel", "india", "juliet", "kilo", "lima", "mike", "november", "oscar", "papa", "quebec", "romeo", "sierra", "tango", "uniform", "victor", "xray", "yankee", "zulu"]
```

**Comment by franc-ist** [comment]
The [Standard Galactic Alphabet](www.shikadi.net/keenwiki/Standard_Galactic_Alphabet) (Minecraft enchanting table language) is just a substitution cipher, where each letter in the Latin alphabet has been substituted with a different symbol.

For example, 
```
Iℸ ̣  ╎ᓭ ⍑ᔑ∷↸ ℸ ̣ 𝙹 ᒷ∷ᔑᓭᒷ ʖꖎ⚍ᒷ 𝙹∷ ∷ᒷ↸ ╎リꖌ.
```
reads as
```
It is hard to erase blue or red ink.
```
when translated. I assume you could map each SGA symbol to its Latin counterpart in a dictionary and just iterate through that?

**Comment by lukasgabriel** [comment]
@brandonskerritt Would the NATO alphabet be covered by 'First letter of every word'?
@franc-ist Thanks, if it's just a simple substitution cipher, I'll try and implement it.

**Comment by brandonskerritt** [comment]
> @brandonskerritt Would the NATO alphabet be covered by 'First letter of every word'?
> @franc-ist Thanks, if it's just a simple substitution cipher, I'll try and implement it.

Yes, it would be! I tried to implement a nice recursive function for it, but I had bigger problems at the same :yum: 

Check out the documentation too :)
https://docs.ciphey.online/en/latest/makingCiphers.html

**Comment by lukasgabriel** [comment]
> 
> 
> The [Standard Galactic Alphabet](www.shikadi.net/keenwiki/Standard_Galactic_Alphabet) (Minecraft enchanting table language) is just a substitution cipher, where each letter in the Latin alphabet has been substituted with a different symbol.
> 
> For example,
> 
> ```
> Iℸ ̣  ╎ᓭ ⍑ᔑ∷↸ ℸ ̣ 𝙹 ᒷ∷ᔑᓭᒷ ʖꖎ⚍ᒷ 𝙹∷ ∷ᒷ↸ ╎リꖌ.
> ```
> 
> reads as
> 
> ```
> It is hard to erase blue or red ink.
> ```
> 
> when translated. I assume you could map each SGA symbol to its Latin counterpart in a dictionary and just iterate through that?

Implemented 👍

**Comment by lukasgabriel** [comment]
Idea: https://en.wikipedia.org/wiki/Four-square_cipher

**Comment by brandonskerritt** [comment]
> Idea: https://en.wikipedia.org/wiki/Four-square_cipher

How easy is this to add? :)

**Comment by lukasgabriel** [comment]
I'd say hard to very hard:
http://practicalcryptography.com/cryptanalysis/stochastic-searching/cryptanalysis-foursquare-cipher/

This goes very in-depth and provides C code examples. Look into the comments also. Much too advanced for me personally.

**Comment by SkeletalDemise** [comment]
Why is Base8 (octal) under not done? Octal is already implemented unless I'm missed something. Just wondering.

**Comment by brandonskerritt** [comment]
> Why is Base8 (octal) under not done? Octal is already implemented unless I'm missing something. Just wondering.

fixed this!

**Comment by mendel3** [comment]
More ideas of easy ciphers to implement:
ROT47/ASCII Shift
A1Z26

**Comment by bee-san** [comment]
> More ideas of easy ciphers to implement:
> ROT47/ASCII Shift
> A1Z26

Added thanks! :D

**Comment by lukasgabriel** [comment]
We're starting to move these feature requests to their own issues to take advantage of GitHub's Project Boards feature and keep things clear & easy to track.

**Comment by lukasgabriel** [comment]
@all-contributors please add @lukasgabriel for ideas

**Comment by ArnaubHie** [comment]
How Is

**Comment by Jamzkil** [comment]
Please help me in my  our issue but  i dont  know  what am doing..

**Comment by eabase** [comment]
I'm surprised nobody seem to have added `Enigma` already. Would be cool to see some use for that. 
There are both crackers and en/decoders in many different languages. Another cool way is to use the MCMC approach which seem very nice for cracking Enigma style ciphers. 

Here's a brief collection:

* http://www.cs.cornell.edu/courses/cs3110/2020sp/a1/ 
* https://www.dcode.fr/enigma-machine-cipher

* https://www.schneier.com/wp-content/uploads/2015/03/ENIGMA-2.zip (Encipher algo)
* https://github.com/inewell/enigma (Java)
* https://github.com/mikepound/enigma
* https://www.codeproject.com/Articles/831015/ENIGMA

* https://github.com/Code-Bullet/Enigma-Simulator (processing)
* https://github.com/NationalSecurityAgency/enigma-simulator (Python)
* https://github.com/NationalSecurityAgency/enigma-simulator/commit/0aa2b5d2685f79ccb85c12dac9fd618522c4206f 	(CLI-tool to simulator)
* https://github.com/emedvedev/enigma
* https://github.com/cedricbonhomme/pyEnigma
* https://github.com/jameslyons/pycipher
* https://github.com/jameslyons/pycipher/blob/master/pycipher/enigma.py
* https://github.com/benelsen/enigma (JS)

Using MCMC, but is not completely clear this is actually cracking Enigma.
What is cool, is that the algo is very simple to implement. 

* https://towardsdatascience.com/breaking-the-enigma-code-in-python-with-mcmc-marvel-themed-9ceb358dd8ae
* https://github.com/JackWillz/Projects/blob/master/MCMC%20-%20Enigma%20Thanos/BreakEnigma.ipynb
* https://gist.github.com/JackWillz/d99deb8323540216bcaa932150ad71e0#file-mcmc-py
